---
# prepare all machines for provisioning
- import_playbook: initial.yml
# deploy the base kubernetes cluster
- import_playbook: k8s.yml
# install third party applications
- import_playbook: third_party.yml
# configure CI/CD
- import_playbook: cicd.yml
