[cp]
kmn1 ansible_host=192.168.88.41

[dp]
kwn1 ansible_host=192.168.88.42
kwn2 ansible_host=192.168.88.43
; kwn3 ansible_host=192.168.88.44

[mon]
mon1 ansible_host=192.168.88.44

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=core
ansible_password=foobar
ansible_become=true
